services:
  - type: web
    name: co-razer
    env: node
    plan: free
    buildCommand: npm install && npm run build:css
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: GOOGLE_API_KEY
        sync: false
